image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore

tasks:
  - name: Prepare deps
    init: clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"1.1.1"},cider/cider-nrepl {:mvn/version,"0.47.1"}}}' -P
  - name: INSTRUCTIONS
    command: code doc/INSTRUCTIONS.md
