image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore

tasks:
  - name: Prepare deps
    init: clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"0.8.3"},cider/cider-nrepl {:mvn/version,"0.26.0"}}}' -P
  - name: INSTRUCTIONS
    command: doc/INSTRUCTIONS.md src/get_started/hello_repl.clj src/get_started/welcome_to_clojure.clj code src/get_started/hello_paredit.clj
